name: Check README

on: [push]

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: README must exist
        run: |
          if [ ! -f README.md ]; then
            echo "README.md がありません"
            exit 1
          fi

          echo "README.md が存在します"